// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoWo77j439L9XvBiQ-iDJJXm8G2yYCiRM',
    appId: '1:184699776588:web:3a4c8a9c88456eb7f20ee9',
    messagingSenderId: '184699776588',
    projectId: 'fasum-598a2',
    authDomain: 'fasum-598a2.firebaseapp.com',
    storageBucket: 'fasum-598a2.firebasestorage.app',
    measurementId: 'G-PL2CQTSWRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbOL196GdtTzCiOknYcl3dTJkZfx6UOM',
    appId: '1:184699776588:android:94df2402eb2b5d14f20ee9',
    messagingSenderId: '184699776588',
    projectId: 'fasum-598a2',
    storageBucket: 'fasum-598a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCueopfTwcFgpoTgftxlYvoZUOOqKGHvoc',
    appId: '1:184699776588:ios:a331e738dbae0df0f20ee9',
    messagingSenderId: '184699776588',
    projectId: 'fasum-598a2',
    storageBucket: 'fasum-598a2.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCueopfTwcFgpoTgftxlYvoZUOOqKGHvoc',
    appId: '1:184699776588:ios:a331e738dbae0df0f20ee9',
    messagingSenderId: '184699776588',
    projectId: 'fasum-598a2',
    storageBucket: 'fasum-598a2.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoWo77j439L9XvBiQ-iDJJXm8G2yYCiRM',
    appId: '1:184699776588:web:d951dcb5d6e50bc6f20ee9',
    messagingSenderId: '184699776588',
    projectId: 'fasum-598a2',
    authDomain: 'fasum-598a2.firebaseapp.com',
    storageBucket: 'fasum-598a2.firebasestorage.app',
    measurementId: 'G-EJ6M7677CR',
  );
}
